development:
  adapter: postgresql
  database: hiddenhook_development
  host: localhost
test:
  adapter: postgresql
  database: hiddenhook_development
  host: localhost

production:
  adapter: postgresql
  database: hiddenhook_production
  host: localhost